FROM python:3.11-bookworm

ENV POETRY_VERSION=1.8.4

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /app
COPY . .
RUN poetry config virtualenvs.create false \
    && poetry add uvicorn[standard] \
    && poetry install --no-interaction --no-ansi

EXPOSE 8000

ENTRYPOINT [ "/app/docker-entrypoint.prod.sh" ]
